require('options/filetree')
require('options/lsp')
require('options/codecompletion')
require('options/statusline')
require('options/treesitter')
require('options/dashboard')
require('options/telescope')
