local kind_icons = {
    Text = "",
    Method = "󱀍",
    Function = "󰊕",
    Constructor = "",
    Field = "󰇽",
    Variable = "󰂡",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Property = "󰜢",
    Unit = "",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "",
    Color = "󰏘",
    File = "󰈙",
    Reference = "",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "󰏿",
    Struct = "",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "󰅲",
}

local header = {
    [[]],
    [[]],
    [[]],
    [[]],
    [[]],
    [[]],
    [[]],
    [[]],
    [[]],
    [[]],
    [[                                        ]],
    [[                  ;kOl.                 ]],
    [[                 cXMMWx.                ]],
    [[                '0MMMMWl                ]],
    [[  .ldo:.   ..''..lKWMNx,.','.    ,ldd,  ]],
    [[  .lNMNo,lxkkkOOOdolllokkOOOkkd;:KMWk.  ]],
    [[    ':o0Kd;...'',ol. ,d:'''..,lOXxc;.   ]],
    [[     .kK: .oOKOd,      .ckK0x; .kK:     ]],
    [[     cNo .kWM0:.        .'xWMX; ,Kk.    ]],
    [[   ..dWl .dNMd            ;KW0, '0O,..  ]],
    [[ .l0xkNk..c0WK;          .xNXd. cNOd0x' ]],
    [[  .'..xNx,'',clc'      .;ll;'''lXK;.'.  ]],
    [[      .xNKl'   .'.     ..   .:kN0;      ]],
    [[        ;kXXko;.        .,cxKX0l.       ]],
    [[          .cxKNXOl.  .:xKNNOo,.         ]],
    [[             .,lONKdlkNKd:.             ]],
    [[                 :0WMXo.                ]],
    [[                  'x0c                  ]],
    [[                    .                   ]],
    [[]],
    [[]],
    [[]],
    [[]],
    [[]],
}

return {
    lspicons = kind_icons,
    header = header
}
